name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: wasm-pack-action
        uses: jetli/wasm-pack-action@v0.3.0

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            default: true
            
      - run: cargo install wasm-pack
      
      - run: wasm-pack build
      
      - uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: pkg # The folder the action should deploy.
